# Generated by Django 5.0.2 on 2024-02-18 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_date_product_image_product_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='catagory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='catagory',
            new_name='category',
        ),
    ]
